package models

// SignalType represents the type of trading signal.
type SignalType string

const (
	// SignalBuy indicates a buy signal.
	SignalBuy SignalType = "buy"
	// SignalSell indicates a sell signal.
	SignalSell SignalType = "sell"
	// SignalHold indicates no action should be taken.
	SignalHold SignalType = "hold"
)

// SignalStrength represents the confidence level of a signal.
type SignalStrength string

const (
	// SignalStrengthWeak indicates low confidence.
	SignalStrengthWeak SignalStrength = "weak"
	// SignalStrengthModerate indicates medium confidence.
	SignalStrengthModerate SignalStrength = "moderate"
	// SignalStrengthStrong indicates high confidence.
	SignalStrengthStrong SignalStrength = "strong"
)

// Signal represents a trading signal generated by a strategy.
type Signal struct {
	// Symbol is the ticker symbol the signal is for.
	Symbol string `json:"symbol"`
	// Type is the signal type (buy/sell/hold).
	Type SignalType `json:"type"`
	// Strength indicates the confidence level.
	Strength SignalStrength `json:"strength"`
	// Price is the suggested entry/exit price.
	Price float64 `json:"price"`
	// Quantity is the suggested position size.
	Quantity float64 `json:"quantity"`
	// StopLoss is the suggested stop-loss price.
	StopLoss float64 `json:"stop_loss,omitempty"`
	// TakeProfit is the suggested take-profit price.
	TakeProfit float64 `json:"take_profit,omitempty"`
	// Reason provides context for the signal.
	Reason string `json:"reason"`
	// StrategyName is the name of the strategy that generated this signal.
	StrategyName string `json:"strategy_name"`
}
